const products = [
  {
    _id: '1',
    name: 'Rainforesters',
    image: '/shoes/mens-forest.png',
    description:
      'Sleek in design, tropical forest by nature.',
    brand: 'Custom',
    category: 'Mens',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Urbans',
    image: '/shoes/mens-leather-brown.png',
    description:
      'A combination of hi-top and formal leather like none other.',
    brand: 'Custom',
    category: 'Mens',
    price: 89.99,
    countInStock: 5,
    rating: 3,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Ranchers',
    image: '/shoes/mens-leather.png',
    description:
      'Innovative leather design, tough exterior and arch-supporting interior.',
    brand: 'Custom',
    category: 'Mens',
    price: 89.99,
    countInStock: 11,
    rating: 5,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'City Sneakers',
    image: '/shoes/mens-sneakers.png',
    description:
      'Eclectic and electric. The classic hi-top, reimagined.',
    brand: 'Custom',
    category: 'Mens',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 10,
  },
  {
    _id: '5',
    name: 'Polars',
    image: '/shoes/unisex-arctic-camo.png',
    description:
      'Our icy blue camo concept inspired by the Arctic.',
    brand: 'Custom',
    category: 'Unisex',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Deserters',
    image: '/shoes/unisex-desert.png',
    description:
      'A refined concept inspired by the sands of time.',
    brand: 'Custom',
    category: 'Unisex',
    price: 59.99,
    countInStock: 0,
    rating: 4,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'GreyCamo',
    image: '/shoes/unisex-grey-camo.png',
    description:
      'The concrete jungle awaits.',
    brand: 'Custom',
    category: 'Unisex',
    price: 59.99,
    countInStock: 0,
    rating: 4,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Rocky Canyons',
    image: '/shoes/womens-grand-canyon.png',
    description:
      'Perfect for rocky terrain.',
    brand: 'Custom',
    category: 'Womens',
    price: 89.99,
    countInStock: 0,
    rating: 4,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Gym Noirs',
    image: '/shoes/womens-gym-shoes.png',
    description:
      'These kicks are made for the gym.',
    brand: 'Custom',
    category: 'Womens',
    price: 59.99,
    countInStock: 0,
    rating: 4,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Ocean Heels',
    image: '/shoes/womens-ocean.png',
    description:
      'Featuring a design inspired by the ocean, this is the perfect pair of heels.',
    brand: 'Custom',
    category: 'Womens',
    price: 89.99,
    countInStock: 0,
    rating: 4,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Lady Urbans',
    image: '/shoes/womens-semi-formal.png',
    description:
      'When you need to kick it up a notch.',
    brand: 'Custom',
    category: 'Womens',
    price: 59.99,
    countInStock: 0,
    rating: 4,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Tundra Runners',
    image: '/shoes/womens-tundra-runners.png',
    description:
      'These runners are waiting for your next adventure.',
    brand: 'Custom',
    category: 'Womens',
    price: 59.99,
    countInStock: 0,
    rating: 4,
    sizes: ['6', '7', '8', '9', '10'],
    numReviews: 12,
  },
]

export default products
